"""add_asset_and_provider_fields

Revision ID: 18149a24cbc6
Revises: 0cb0f34a925d
Create Date: 2025-12-26 15:03:07.960857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18149a24cbc6'
down_revision: Union[str, None] = '0cb0f34a925d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset', sa.String(length=100), nullable=False, comment='Provider asset ID (USDT_TRX_TEST4, ETH_TEST5)'))
    op.add_column('assets', sa.Column('provider', sa.String(length=50), server_default='fireblocks', nullable=False, comment='Custody provider (fireblocks, self_custody)'))
    op.drop_constraint(op.f('uq_asset_blockchain_contract_testnet'), 'assets', type_='unique')
    op.create_index(op.f('ix_assets_asset'), 'assets', ['asset'], unique=False)
    op.create_index(op.f('ix_assets_provider'), 'assets', ['provider'], unique=False)
    op.create_index('ix_assets_provider_blockchain', 'assets', ['provider', 'blockchain'], unique=False)
    op.create_unique_constraint('uq_asset_provider_asset', 'assets', ['provider', 'asset'])
    op.create_unique_constraint('uq_asset_provider_blockchain_contract_testnet', 'assets', ['provider', 'blockchain', 'contract_address', 'testnet'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_asset_provider_blockchain_contract_testnet', 'assets', type_='unique')
    op.drop_constraint('uq_asset_provider_asset', 'assets', type_='unique')
    op.drop_index('ix_assets_provider_blockchain', table_name='assets')
    op.drop_index(op.f('ix_assets_provider'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset'), table_name='assets')
    op.create_unique_constraint(op.f('uq_asset_blockchain_contract_testnet'), 'assets', ['blockchain', 'contract_address', 'testnet'], postgresql_nulls_not_distinct=False)
    op.drop_column('assets', 'provider')
    op.drop_column('assets', 'asset')
    # ### end Alembic commands ###

