"""init

Revision ID: 0cb0f34a925d
Revises: 
Create Date: 2025-12-26 11:24:50.019184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb0f34a925d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Short symbol (USDT, BTC, ETH)'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='Full display name (Tether USD, Bitcoin)'),
    sa.Column('blockchain', sa.String(length=50), nullable=False, comment='Blockchain (ETHEREUM, TRON, BITCOIN, BSC, SOLANA)'),
    sa.Column('network', sa.String(length=20), nullable=False, comment='Token standard (ERC20, TRC20, BEP20, SPL, NATIVE)'),
    sa.Column('contract_address', sa.String(length=128), nullable=True, comment='Token contract address (null for native coins like ETH, BTC)'),
    sa.Column('testnet', sa.String(length=20), nullable=True, comment='Testnet name (SEPOLIA, SHASTA, HOLESKY) or null for mainnet'),
    sa.Column('decimals', sa.Integer(), nullable=False, comment='Number of decimals'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is asset active for use'),
    sa.Column('is_native', sa.Boolean(), server_default='false', nullable=False, comment='Is native/base coin (ETH, BTC, TRX)'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='Parent asset ID (native coin for tokens, for gas estimation)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Created at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Updated at'),
    sa.ForeignKeyConstraint(['parent_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blockchain', 'contract_address', 'testnet', name='uq_asset_blockchain_contract_testnet')
    )
    op.create_index(op.f('ix_assets_blockchain'), 'assets', ['blockchain'], unique=False)
    op.create_index('ix_assets_blockchain_testnet', 'assets', ['blockchain', 'testnet'], unique=False)
    op.create_index(op.f('ix_assets_contract_address'), 'assets', ['contract_address'], unique=False)
    op.create_index(op.f('ix_assets_parent_id'), 'assets', ['parent_id'], unique=False)
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_index('ix_assets_symbol_blockchain', 'assets', ['symbol', 'blockchain'], unique=False)
    op.create_index(op.f('ix_assets_testnet'), 'assets', ['testnet'], unique=False)
    op.create_table('vaults',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_vault_id', sa.String(length=255), nullable=False, comment='Fireblocks vault ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Vault name'),
    sa.Column('vault_type', sa.String(length=50), nullable=False, comment='Тип vault: hot, warm, cold, regular, operational'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Primary vault для данного типа (основной HOT/WARM/COLD)'),
    sa.Column('min_balance_usd', sa.Numeric(precision=18, scale=2), nullable=True, comment='Минимальный баланс USD (для алертов)'),
    sa.Column('max_balance_usd', sa.Numeric(precision=18, scale=2), nullable=True, comment='Максимальный баланс USD (для auto-rebalance)'),
    sa.Column('target_balance_percent', sa.Integer(), nullable=True, comment='Целевой % от общего баланса (для rebalancing)'),
    sa.Column('auto_refill_enabled', sa.Boolean(), nullable=False, comment='Включен ли auto-refill из WARM'),
    sa.Column('auto_refill_threshold_percent', sa.Integer(), nullable=True, comment='Порог % при котором запускается auto-refill'),
    sa.Column('auto_refill_target_percent', sa.Integer(), nullable=True, comment='Целевой % после auto-refill'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status: creating, available, error, maintenance'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is vault active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Created at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Updated at'),
    sa.Column('description', sa.String(length=500), nullable=True, comment="Описание vault'а для админки"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaults_provider_vault_id'), 'vaults', ['provider_vault_id'], unique=True)
    op.create_index('ix_vaults_type_active', 'vaults', ['vault_type', 'is_active'], unique=False)
    op.create_index('ix_vaults_type_primary', 'vaults', ['vault_type', 'is_primary'], unique=False)
    op.create_index(op.f('ix_vaults_vault_type'), 'vaults', ['vault_type'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vault_id', sa.UUID(), nullable=False, comment='Vault ID'),
    sa.Column('asset_id', sa.UUID(), nullable=False, comment='Asset ID'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='Wallet address'),
    sa.Column('legacy_address', sa.String(length=255), nullable=True, comment='Legacy address (for BTC)'),
    sa.Column('tag', sa.String(length=255), nullable=True, comment='Tag/Memo (for XRP, XLM)'),
    sa.Column('balance', sa.Numeric(precision=36, scale=18), server_default='0', nullable=False, comment='Asset balance'),
    sa.Column('pending_amount', sa.Numeric(precision=36, scale=18), server_default='0', nullable=False, comment='Reserved amount for pending payouts'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Created at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Updated at'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=False)
    op.create_index(op.f('ix_wallets_asset_id'), 'wallets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_wallets_vault_id'), 'wallets', ['vault_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=True, comment='External request ID for tracing (from externalTxId)'),
    sa.Column('provider_tx_id', sa.String(length=255), nullable=False, comment='Fireblocks transaction ID'),
    sa.Column('tx_hash', sa.String(length=255), nullable=True, comment='Transaction hash'),
    sa.Column('vault_id', sa.UUID(), nullable=True, comment='Vault ID'),
    sa.Column('wallet_id', sa.UUID(), nullable=True, comment='Wallet ID'),
    sa.Column('asset_id', sa.UUID(), nullable=True, comment='Asset ID'),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False, comment='Transaction amount'),
    sa.Column('amount_usd', sa.Numeric(precision=36, scale=18), nullable=True, comment='Amount in USD'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Technical status from Fireblocks'),
    sa.Column('num_confirmations', sa.Integer(), nullable=True, comment='Number of confirmations'),
    sa.Column('is_internal', sa.Boolean(), nullable=False, comment='Is internal transfer (whitelist)'),
    sa.Column('source_address', sa.String(length=255), nullable=True, comment='Source address'),
    sa.Column('destination_address', sa.String(length=255), nullable=True, comment='Destination address'),
    sa.Column('raw_webhook_data', sa.Text(), nullable=True, comment='Raw webhook data'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Created at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Updated at'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_asset_id'), 'transactions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_transactions_provider_tx_id'), 'transactions', ['provider_tx_id'], unique=True)
    op.create_index(op.f('ix_transactions_request_id'), 'transactions', ['request_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_tx_hash'), 'transactions', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_transactions_vault_id'), 'transactions', ['vault_id'], unique=False)
    op.create_index(op.f('ix_transactions_wallet_id'), 'transactions', ['wallet_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=50), nullable=False, comment='External request ID for tracing'),
    sa.Column('is_internal', sa.Boolean(), nullable=False, comment='True for whitelist transfers, False for external'),
    sa.Column('vault_id', sa.UUID(), nullable=True, comment='Source vault ID'),
    sa.Column('wallet_id', sa.UUID(), nullable=True, comment='Source wallet ID'),
    sa.Column('asset_id', sa.UUID(), nullable=True, comment='Asset ID'),
    sa.Column('source_address', sa.String(length=255), nullable=True, comment='Source HOT wallet address'),
    sa.Column('currency', sa.String(length=20), nullable=False, comment='Asset symbol (ETH, USDT, TRX)'),
    sa.Column('contract_address', sa.String(length=100), nullable=True, comment='Token contract address (NULL for native tokens)'),
    sa.Column('blockchain', sa.String(length=50), nullable=False, comment='Blockchain (ETHEREUM, TRON, BSC)'),
    sa.Column('network', sa.String(length=20), nullable=True, comment='Network (ERC20, TRC20, BEP20, NATIVE, etc.)'),
    sa.Column('destination_address', sa.String(length=255), nullable=False, comment='Destination wallet address'),
    sa.Column('destination_tag', sa.String(length=255), nullable=True, comment='Destination tag/memo (XRP, XLM, etc.)'),
    sa.Column('to_vault_id', sa.UUID(), nullable=True, comment='Destination vault for internal transfers'),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False, comment='Transfer amount'),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=2), nullable=True, comment='Amount in USD'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='Transfer status'),
    sa.Column('provider_tx_id', sa.String(length=255), nullable=True, comment='Fireblocks transaction ID'),
    sa.Column('tx_hash', sa.String(length=255), nullable=True, comment='Blockchain transaction hash'),
    sa.Column('note', sa.String(length=500), nullable=True, comment='Optional note'),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True, comment='When balance was reserved'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When transfer completed/rejected'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Created at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Updated at'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if failed'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of balance reservation attempts'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_vault_id'], ['vaults.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_asset_id'), 'transfers', ['asset_id'], unique=False)
    op.create_index(op.f('ix_transfers_blockchain'), 'transfers', ['blockchain'], unique=False)
    op.create_index('ix_transfers_blockchain_contract', 'transfers', ['blockchain', 'contract_address'], unique=False)
    op.create_index(op.f('ix_transfers_contract_address'), 'transfers', ['contract_address'], unique=False)
    op.create_index(op.f('ix_transfers_currency'), 'transfers', ['currency'], unique=False)
    op.create_index(op.f('ix_transfers_destination_address'), 'transfers', ['destination_address'], unique=False)
    op.create_index(op.f('ix_transfers_is_internal'), 'transfers', ['is_internal'], unique=False)
    op.create_index(op.f('ix_transfers_provider_tx_id'), 'transfers', ['provider_tx_id'], unique=False)
    op.create_index(op.f('ix_transfers_request_id'), 'transfers', ['request_id'], unique=True)
    op.create_index(op.f('ix_transfers_status'), 'transfers', ['status'], unique=False)
    op.create_index('ix_transfers_status_created', 'transfers', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_transfers_tx_hash'), 'transfers', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_transfers_vault_id'), 'transfers', ['vault_id'], unique=False)
    op.create_index(op.f('ix_transfers_wallet_id'), 'transfers', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_wallet_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_vault_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_tx_hash'), table_name='transfers')
    op.drop_index('ix_transfers_status_created', table_name='transfers')
    op.drop_index(op.f('ix_transfers_status'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_request_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_provider_tx_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_is_internal'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_destination_address'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_currency'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_contract_address'), table_name='transfers')
    op.drop_index('ix_transfers_blockchain_contract', table_name='transfers')
    op.drop_index(op.f('ix_transfers_blockchain'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_asset_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_transactions_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_vault_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_tx_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_request_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_provider_tx_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_asset_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_wallets_vault_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_asset_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_vaults_vault_type'), table_name='vaults')
    op.drop_index('ix_vaults_type_primary', table_name='vaults')
    op.drop_index('ix_vaults_type_active', table_name='vaults')
    op.drop_index(op.f('ix_vaults_provider_vault_id'), table_name='vaults')
    op.drop_table('vaults')
    op.drop_index(op.f('ix_assets_testnet'), table_name='assets')
    op.drop_index('ix_assets_symbol_blockchain', table_name='assets')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_index(op.f('ix_assets_parent_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_contract_address'), table_name='assets')
    op.drop_index('ix_assets_blockchain_testnet', table_name='assets')
    op.drop_index(op.f('ix_assets_blockchain'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###

