from enum import Enum


class TransactionStatusEnum(str, Enum):
    SUBMITTED = "SUBMITTED"
    QUEUED = "QUEUED"
    PENDING_SIGNATURE = "PENDING_SIGNATURE"
    PENDING_AUTHORIZATION = "PENDING_AUTHORIZATION"
    PENDING_3RD_PARTY_MANUAL_APPROVAL = "PENDING_3RD_PARTY_MANUAL_APPROVAL"
    PENDING_3RD_PARTY = "PENDING_3RD_PARTY"
    PENDING = "PENDING"
    BROADCASTING = "BROADCASTING"
    CONFIRMING = "CONFIRMING"
    CONFIRMED = "CONFIRMED"
    COMPLETED = "COMPLETED"
    PENDING_AML_SCREENING = "PENDING_AML_SCREENING"
    PARTIALLY_COMPLETED = "PARTIALLY_COMPLETED"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    BLOCKED = "BLOCKED"


class TransactionOperationEnum(str, Enum):
    TRANSFER = "TRANSFER"
    MINT = "MINT"
    BURN = "BURN"
    CONTRACT_CALL = "CONTRACT_CALL"
    TYPED_MESSAGE = "TYPED_MESSAGE"
    RAW = "RAW"
    ENABLE_ASSET = "ENABLE_ASSET"
    STAKE = "STAKE"
    UNSTAKE = "UNSTAKE"
    APPROVE = "APPROVE"
    WITHDRAW = "WITHDRAW"


class PeerTypeEnum(str, Enum):
    VAULT_ACCOUNT = "VAULT_ACCOUNT"
    EXCHANGE_ACCOUNT = "EXCHANGE_ACCOUNT"
    INTERNAL_WALLET = "INTERNAL_WALLET"
    EXTERNAL_WALLET = "EXTERNAL_WALLET"
    UNMANAGED_WALLET = "UNMANAGED_WALLET"
    ONE_TIME_ADDRESS = "ONE_TIME_ADDRESS"
    NETWORK_CONNECTION = "NETWORK_CONNECTION"
    FIAT_ACCOUNT = "FIAT_ACCOUNT"
    GAS_STATION = "GAS_STATION"
    UNKNOWN = "UNKNOWN"
    CONTRACT = "CONTRACT"
    MULTI_DESTINATION = "MULTI_DESTINATION"
